=== albertojmarun/Practicas_Lenguaje_De_Marcas/XML/concesionario/concesionario.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xs:element name="concesionario">
        <xs:complexType>
            <xs:element name="marca" type="xs:string"/>
            <xs:element name="modelo" type="xs:string"/>
            <xs:choice>
                <xs:element name="cilindrada" type="xs:decimal"/>
                <xs:element name="caballos" type="xs:decimal"/>
            </xs:choice>
            <xs:element name="combustible" type="xs:string"/>
            <xs:element name="precio" type="xs:positiveInteger"/>
            <xs:element name="aÃ±o" use="optional" type="xs:date"/>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="interesado" type="xs:string"/>
            <xs:element name="fecha_limite" type="xs:dateTime"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== albertojmarun/Practicas_Lenguaje_De_Marcas/XML/concesionario/concesionario.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<concesionario
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="concesionario.xsd"
provincia="malaga">

    <coches matricula="0511LDP">
        <marca> </marca>
        <modelo> </modelo>
        <cilindrada> </cilindrada>
        <combustible> </combustible>
        <precio> </precio>
        <año> </año>
        <color> </color>
        <interesado> </interesado>
        <fecha_limite> </fecha_limite>
    </coches>
</concesionario>
