<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!--
    @author: Alberto J. Marun I.
    @version: 1.0
    @date: February 02, 2021.
-->
<!DOCTYPE mensaje [
    <!ELEMENT mensaje (remite, destinatario, asunto, texto)>
    <!ELEMENT remite (nombre, email)>
    <!ELEMENT destinatario (nombre, email)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT texto (parrafo*)>
        <!ELEMENT parrafo (#PCDATA)>
]>

<mensaje>
    <remite>
        <nombre> Alfredo Reino </nombre>
        <email> alf@ibium.com </email>
    </remite>
    <destinatario>
        <nombre> Bill Clinton </nombre>
        <email> president@whitehouse.gov</email>
    </destinatario>
    <asunto> Hola Bill </asunto>
    <texto>
        <parrafo> ¿Hola qué tal?</parrafo>
        <parrafo> Hace mucho tiempo que no escribes. A ver si llamas y quedamos pronto. </parrafo>
        <parrafo> He estado ocupado, asuntos de Estado </parrafo>
    </texto>
</mensaje>